<?php

namespace Database\Seeders;

use App\Models\Kabupaten;
use Illuminate\Database\Seeder;

class KabupatenSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $regencies = array(
      array('id' => '1101','province' => '11','name' => 'KAB. ACEH SELATAN'),
      array('id' => '1102','province' => '11','name' => 'KAB. ACEH TENGGARA'),
      array('id' => '1103','province' => '11','name' => 'KAB. ACEH TIMUR'),
      array('id' => '1104','province' => '11','name' => 'KAB. ACEH TENGAH'),
      array('id' => '1105','province' => '11','name' => 'KAB. ACEH BARAT'),
      array('id' => '1106','province' => '11','name' => 'KAB. ACEH BESAR'),
      array('id' => '1107','province' => '11','name' => 'KAB. PIDIE'),
      array('id' => '1108','province' => '11','name' => 'KAB. ACEH UTARA'),
      array('id' => '1109','province' => '11','name' => 'KAB. SIMEULUE'),
      array('id' => '1110','province' => '11','name' => 'KAB. ACEH SINGKIL'),
      array('id' => '1111','province' => '11','name' => 'KAB. BIREUEN'),
      array('id' => '1112','province' => '11','name' => 'KAB. ACEH BARAT DAYA'),
      array('id' => '1113','province' => '11','name' => 'KAB. GAYO LUES'),
      array('id' => '1114','province' => '11','name' => 'KAB. ACEH JAYA'),
      array('id' => '1115','province' => '11','name' => 'KAB. NAGAN RAYA'),
      array('id' => '1116','province' => '11','name' => 'KAB. ACEH TAMIANG'),
      array('id' => '1117','province' => '11','name' => 'KAB. BENER MERIAH'),
      array('id' => '1118','province' => '11','name' => 'KAB. PIDIE JAYA'),
      array('id' => '1171','province' => '11','name' => 'KOTA BANDA ACEH'),
      array('id' => '1172','province' => '11','name' => 'KOTA SABANG'),
      array('id' => '1173','province' => '11','name' => 'KOTA LHOKSEUMAWE'),
      array('id' => '1174','province' => '11','name' => 'KOTA LANGSA'),
      array('id' => '1175','province' => '11','name' => 'KOTA SUBULUSSALAM'),
      array('id' => '1201','province' => '12','name' => 'KAB. TAPANULI TENGAH'),
      array('id' => '1202','province' => '12','name' => 'KAB. TAPANULI UTARA'),
      array('id' => '1203','province' => '12','name' => 'KAB. TAPANULI SELATAN'),
      array('id' => '1204','province' => '12','name' => 'KAB. NIAS'),
      array('id' => '1205','province' => '12','name' => 'KAB. LANGKAT'),
      array('id' => '1206','province' => '12','name' => 'KAB. KARO'),
      array('id' => '1207','province' => '12','name' => 'KAB. DELI SERDANG'),
      array('id' => '1208','province' => '12','name' => 'KAB. SIMALUNGUN'),
      array('id' => '1209','province' => '12','name' => 'KAB. ASAHAN'),
      array('id' => '1210','province' => '12','name' => 'KAB. LABUHANBATU'),
      array('id' => '1211','province' => '12','name' => 'KAB. DAIRI'),
      array('id' => '1212','province' => '12','name' => 'KAB. TOBA SAMOSIR'),
      array('id' => '1213','province' => '12','name' => 'KAB. MANDAILING NATAL'),
      array('id' => '1214','province' => '12','name' => 'KAB. NIAS SELATAN'),
      array('id' => '1215','province' => '12','name' => 'KAB. PAKPAK BHARAT'),
      array('id' => '1216','province' => '12','name' => 'KAB. HUMBANG HASUNDUTAN'),
      array('id' => '1217','province' => '12','name' => 'KAB. SAMOSIR'),
      array('id' => '1218','province' => '12','name' => 'KAB. SERDANG BEDAGAI'),
      array('id' => '1219','province' => '12','name' => 'KAB. BATU BARA'),
      array('id' => '1220','province' => '12','name' => 'KAB. PADANG LAWAS UTARA'),
      array('id' => '1221','province' => '12','name' => 'KAB. PADANG LAWAS'),
      array('id' => '1222','province' => '12','name' => 'KAB. LABUHANBATU SELATAN'),
      array('id' => '1223','province' => '12','name' => 'KAB. LABUHANBATU UTARA'),
      array('id' => '1224','province' => '12','name' => 'KAB. NIAS UTARA'),
      array('id' => '1225','province' => '12','name' => 'KAB. NIAS BARAT'),
      array('id' => '1271','province' => '12','name' => 'KOTA MEDAN'),
      array('id' => '1272','province' => '12','name' => 'KOTA PEMATANGSIANTAR'),
      array('id' => '1273','province' => '12','name' => 'KOTA SIBOLGA'),
      array('id' => '1274','province' => '12','name' => 'KOTA TANJUNG BALAI'),
      array('id' => '1275','province' => '12','name' => 'KOTA BINJAI'),
      array('id' => '1276','province' => '12','name' => 'KOTA TEBING TINGGI'),
      array('id' => '1277','province' => '12','name' => 'KOTA PADANGSIDIMPUAN'),
      array('id' => '1278','province' => '12','name' => 'KOTA GUNUNGSITOLI'),
      array('id' => '1301','province' => '13','name' => 'KAB. PESISIR SELATAN'),
      array('id' => '1302','province' => '13','name' => 'KAB. SOLOK'),
      array('id' => '1303','province' => '13','name' => 'KAB. SIJUNJUNG'),
      array('id' => '1304','province' => '13','name' => 'KAB. TANAH DATAR'),
      array('id' => '1305','province' => '13','name' => 'KAB. PADANG PARIAMAN'),
      array('id' => '1306','province' => '13','name' => 'KAB. AGAM'),
      array('id' => '1307','province' => '13','name' => 'KAB. LIMA PULUH KOTA'),
      array('id' => '1308','province' => '13','name' => 'KAB. PASAMAN'),
      array('id' => '1309','province' => '13','name' => 'KAB. KEPULAUAN MENTAWAI'),
      array('id' => '1310','province' => '13','name' => 'KAB. DHARMASRAYA'),
      array('id' => '1311','province' => '13','name' => 'KAB. SOLOK SELATAN'),
      array('id' => '1312','province' => '13','name' => 'KAB. PASAMAN BARAT'),
      array('id' => '1371','province' => '13','name' => 'KOTA PADANG'),
      array('id' => '1372','province' => '13','name' => 'KOTA SOLOK'),
      array('id' => '1373','province' => '13','name' => 'KOTA SAWAHLUNTO'),
      array('id' => '1374','province' => '13','name' => 'KOTA PADANG PANJANG'),
      array('id' => '1375','province' => '13','name' => 'KOTA BUKITTINGGI'),
      array('id' => '1376','province' => '13','name' => 'KOTA PAYAKUMBUH'),
      array('id' => '1377','province' => '13','name' => 'KOTA PARIAMAN'),
      array('id' => '1401','province' => '14','name' => 'KAB. KAMPAR'),
      array('id' => '1402','province' => '14','name' => 'KAB. INDRAGIRI HULU'),
      array('id' => '1403','province' => '14','name' => 'KAB. BENGKALIS'),
      array('id' => '1404','province' => '14','name' => 'KAB. INDRAGIRI HILIR'),
      array('id' => '1405','province' => '14','name' => 'KAB. PELALAWAN'),
      array('id' => '1406','province' => '14','name' => 'KAB. ROKAN HULU'),
      array('id' => '1407','province' => '14','name' => 'KAB. ROKAN HILIR'),
      array('id' => '1408','province' => '14','name' => 'KAB. SIAK'),
      array('id' => '1409','province' => '14','name' => 'KAB. KUANTAN SINGINGI'),
      array('id' => '1410','province' => '14','name' => 'KAB. KEPULAUAN MERANTI'),
      array('id' => '1471','province' => '14','name' => 'KOTA PEKANBARU'),
      array('id' => '1472','province' => '14','name' => 'KOTA DUMAI'),
      array('id' => '1501','province' => '15','name' => 'KAB. KERINCI'),
      array('id' => '1502','province' => '15','name' => 'KAB. MERANGIN'),
      array('id' => '1503','province' => '15','name' => 'KAB. SAROLANGUN'),
      array('id' => '1504','province' => '15','name' => 'KAB. BATANGHARI'),
      array('id' => '1505','province' => '15','name' => 'KAB. MUARO JAMBI'),
      array('id' => '1506','province' => '15','name' => 'KAB. TANJUNG JABUNG BARAT'),
      array('id' => '1507','province' => '15','name' => 'KAB. TANJUNG JABUNG TIMUR'),
      array('id' => '1508','province' => '15','name' => 'KAB. BUNGO'),
      array('id' => '1509','province' => '15','name' => 'KAB. TEBO'),
      array('id' => '1571','province' => '15','name' => 'KOTA JAMBI'),
      array('id' => '1572','province' => '15','name' => 'KOTA SUNGAI PENUH'),
      array('id' => '1601','province' => '16','name' => 'KAB. OGAN KOMERING ULU'),
      array('id' => '1602','province' => '16','name' => 'KAB. OGAN KOMERING ILIR'),
      array('id' => '1603','province' => '16','name' => 'KAB. MUARA ENIM'),
      array('id' => '1604','province' => '16','name' => 'KAB. LAHAT'),
      array('id' => '1605','province' => '16','name' => 'KAB. MUSI RAWAS'),
      array('id' => '1606','province' => '16','name' => 'KAB. MUSI BANYUASIN'),
      array('id' => '1607','province' => '16','name' => 'KAB. BANYUASIN'),
      array('id' => '1608','province' => '16','name' => 'KAB. OGAN KOMERING ULU TIMUR'),
      array('id' => '1609','province' => '16','name' => 'KAB. OGAN KOMERING ULU SELATAN'),
      array('id' => '1610','province' => '16','name' => 'KAB. OGAN ILIR'),
      array('id' => '1611','province' => '16','name' => 'KAB. EMPAT LAWANG'),
      array('id' => '1612','province' => '16','name' => 'KAB. PENUKAL ABAB LEMATANG ILIR'),
      array('id' => '1613','province' => '16','name' => 'KAB. MUSI RAWAS UTARA'),
      array('id' => '1671','province' => '16','name' => 'KOTA PALEMBANG'),
      array('id' => '1672','province' => '16','name' => 'KOTA PAGAR ALAM'),
      array('id' => '1673','province' => '16','name' => 'KOTA LUBUK LINGGAU'),
      array('id' => '1674','province' => '16','name' => 'KOTA PRABUMULIH'),
      array('id' => '1701','province' => '17','name' => 'KAB. BENGKULU SELATAN'),
      array('id' => '1702','province' => '17','name' => 'KAB. REJANG LEBONG'),
      array('id' => '1703','province' => '17','name' => 'KAB. BENGKULU UTARA'),
      array('id' => '1704','province' => '17','name' => 'KAB. KAUR'),
      array('id' => '1705','province' => '17','name' => 'KAB. SELUMA'),
      array('id' => '1706','province' => '17','name' => 'KAB. MUKO MUKO'),
      array('id' => '1707','province' => '17','name' => 'KAB. LEBONG'),
      array('id' => '1708','province' => '17','name' => 'KAB. KEPAHIANG'),
      array('id' => '1709','province' => '17','name' => 'KAB. BENGKULU TENGAH'),
      array('id' => '1771','province' => '17','name' => 'KOTA BENGKULU'),
      array('id' => '1801','province' => '18','name' => 'KAB. LAMPUNG SELATAN'),
      array('id' => '1802','province' => '18','name' => 'KAB. LAMPUNG TENGAH'),
      array('id' => '1803','province' => '18','name' => 'KAB. LAMPUNG UTARA'),
      array('id' => '1804','province' => '18','name' => 'KAB. LAMPUNG BARAT'),
      array('id' => '1805','province' => '18','name' => 'KAB. TULANG BAWANG'),
      array('id' => '1806','province' => '18','name' => 'KAB. TANGGAMUS'),
      array('id' => '1807','province' => '18','name' => 'KAB. LAMPUNG TIMUR'),
      array('id' => '1808','province' => '18','name' => 'KAB. WAY KANAN'),
      array('id' => '1809','province' => '18','name' => 'KAB. PESAWARAN'),
      array('id' => '1810','province' => '18','name' => 'KAB. PRINGSEWU'),
      array('id' => '1811','province' => '18','name' => 'KAB. MESUJI'),
      array('id' => '1812','province' => '18','name' => 'KAB. TULANG BAWANG BARAT'),
      array('id' => '1813','province' => '18','name' => 'KAB. PESISIR BARAT'),
      array('id' => '1871','province' => '18','name' => 'KOTA BANDAR LAMPUNG'),
      array('id' => '1872','province' => '18','name' => 'KOTA METRO'),
      array('id' => '1901','province' => '19','name' => 'KAB. BANGKA'),
      array('id' => '1902','province' => '19','name' => 'KAB. BELITUNG'),
      array('id' => '1903','province' => '19','name' => 'KAB. BANGKA SELATAN'),
      array('id' => '1904','province' => '19','name' => 'KAB. BANGKA TENGAH'),
      array('id' => '1905','province' => '19','name' => 'KAB. BANGKA BARAT'),
      array('id' => '1906','province' => '19','name' => 'KAB. BELITUNG TIMUR'),
      array('id' => '1971','province' => '19','name' => 'KOTA PANGKAL PINANG'),
      array('id' => '2101','province' => '21','name' => 'KAB. BINTAN'),
      array('id' => '2102','province' => '21','name' => 'KAB. KARIMUN'),
      array('id' => '2103','province' => '21','name' => 'KAB. NATUNA'),
      array('id' => '2104','province' => '21','name' => 'KAB. LINGGA'),
      array('id' => '2105','province' => '21','name' => 'KAB. KEPULAUAN ANAMBAS'),
      array('id' => '2171','province' => '21','name' => 'KOTA BATAM'),
      array('id' => '2172','province' => '21','name' => 'KOTA TANJUNG PINANG'),
      array('id' => '3101','province' => '31','name' => 'KAB. ADM. KEP. SERIBU'),
      array('id' => '3171','province' => '31','name' => 'KOTA ADM. JAKARTA PUSAT'),
      array('id' => '3172','province' => '31','name' => 'KOTA ADM. JAKARTA UTARA'),
      array('id' => '3173','province' => '31','name' => 'KOTA ADM. JAKARTA BARAT'),
      array('id' => '3174','province' => '31','name' => 'KOTA ADM. JAKARTA SELATAN'),
      array('id' => '3175','province' => '31','name' => 'KOTA ADM. JAKARTA TIMUR'),
      array('id' => '3201','province' => '32','name' => 'KAB. BOGOR'),
      array('id' => '3202','province' => '32','name' => 'KAB. SUKABUMI'),
      array('id' => '3203','province' => '32','name' => 'KAB. CIANJUR'),
      array('id' => '3204','province' => '32','name' => 'KAB. BANDUNG'),
      array('id' => '3205','province' => '32','name' => 'KAB. GARUT'),
      array('id' => '3206','province' => '32','name' => 'KAB. TASIKMALAYA'),
      array('id' => '3207','province' => '32','name' => 'KAB. CIAMIS'),
      array('id' => '3208','province' => '32','name' => 'KAB. KUNINGAN'),
      array('id' => '3209','province' => '32','name' => 'KAB. CIREBON'),
      array('id' => '3210','province' => '32','name' => 'KAB. MAJALENGKA'),
      array('id' => '3211','province' => '32','name' => 'KAB. SUMEDANG'),
      array('id' => '3212','province' => '32','name' => 'KAB. INDRAMAYU'),
      array('id' => '3213','province' => '32','name' => 'KAB. SUBANG'),
      array('id' => '3214','province' => '32','name' => 'KAB. PURWAKARTA'),
      array('id' => '3215','province' => '32','name' => 'KAB. KARAWANG'),
      array('id' => '3216','province' => '32','name' => 'KAB. BEKASI'),
      array('id' => '3217','province' => '32','name' => 'KAB. BANDUNG BARAT'),
      array('id' => '3218','province' => '32','name' => 'KAB. PANGANDARAN'),
      array('id' => '3271','province' => '32','name' => 'KOTA BOGOR'),
      array('id' => '3272','province' => '32','name' => 'KOTA SUKABUMI'),
      array('id' => '3273','province' => '32','name' => 'KOTA BANDUNG'),
      array('id' => '3274','province' => '32','name' => 'KOTA CIREBON'),
      array('id' => '3275','province' => '32','name' => 'KOTA BEKASI'),
      array('id' => '3276','province' => '32','name' => 'KOTA DEPOK'),
      array('id' => '3277','province' => '32','name' => 'KOTA CIMAHI'),
      array('id' => '3278','province' => '32','name' => 'KOTA TASIKMALAYA'),
      array('id' => '3279','province' => '32','name' => 'KOTA BANJAR'),
      array('id' => '3301','province' => '33','name' => 'KAB. CILACAP'),
      array('id' => '3302','province' => '33','name' => 'KAB. BANYUMAS'),
      array('id' => '3303','province' => '33','name' => 'KAB. PURBALINGGA'),
      array('id' => '3304','province' => '33','name' => 'KAB. BANJARNEGARA'),
      array('id' => '3305','province' => '33','name' => 'KAB. KEBUMEN'),
      array('id' => '3306','province' => '33','name' => 'KAB. PURWOREJO'),
      array('id' => '3307','province' => '33','name' => 'KAB. WONOSOBO'),
      array('id' => '3308','province' => '33','name' => 'KAB. MAGELANG'),
      array('id' => '3309','province' => '33','name' => 'KAB. BOYOLALI'),
      array('id' => '3310','province' => '33','name' => 'KAB. KLATEN'),
      array('id' => '3311','province' => '33','name' => 'KAB. SUKOHARJO'),
      array('id' => '3312','province' => '33','name' => 'KAB. WONOGIRI'),
      array('id' => '3313','province' => '33','name' => 'KAB. KARANGANYAR'),
      array('id' => '3314','province' => '33','name' => 'KAB. SRAGEN'),
      array('id' => '3315','province' => '33','name' => 'KAB. GROBOGAN'),
      array('id' => '3316','province' => '33','name' => 'KAB. BLORA'),
      array('id' => '3317','province' => '33','name' => 'KAB. REMBANG'),
      array('id' => '3318','province' => '33','name' => 'KAB. PATI'),
      array('id' => '3319','province' => '33','name' => 'KAB. KUDUS'),
      array('id' => '3320','province' => '33','name' => 'KAB. JEPARA'),
      array('id' => '3321','province' => '33','name' => 'KAB. DEMAK'),
      array('id' => '3322','province' => '33','name' => 'KAB. SEMARANG'),
      array('id' => '3323','province' => '33','name' => 'KAB. TEMANGGUNG'),
      array('id' => '3324','province' => '33','name' => 'KAB. KENDAL'),
      array('id' => '3325','province' => '33','name' => 'KAB. BATANG'),
      array('id' => '3326','province' => '33','name' => 'KAB. PEKALONGAN'),
      array('id' => '3327','province' => '33','name' => 'KAB. PEMALANG'),
      array('id' => '3328','province' => '33','name' => 'KAB. TEGAL'),
      array('id' => '3329','province' => '33','name' => 'KAB. BREBES'),
      array('id' => '3371','province' => '33','name' => 'KOTA MAGELANG'),
      array('id' => '3372','province' => '33','name' => 'KOTA SURAKARTA'),
      array('id' => '3373','province' => '33','name' => 'KOTA SALATIGA'),
      array('id' => '3374','province' => '33','name' => 'KOTA SEMARANG'),
      array('id' => '3375','province' => '33','name' => 'KOTA PEKALONGAN'),
      array('id' => '3376','province' => '33','name' => 'KOTA TEGAL'),
      array('id' => '3401','province' => '34','name' => 'KAB. KULON PROGO'),
      array('id' => '3402','province' => '34','name' => 'KAB. BANTUL'),
      array('id' => '3403','province' => '34','name' => 'KAB. GUNUNGKIDUL'),
      array('id' => '3404','province' => '34','name' => 'KAB. SLEMAN'),
      array('id' => '3471','province' => '34','name' => 'KOTA YOGYAKARTA'),
      array('id' => '3501','province' => '35','name' => 'KAB. PACITAN'),
      array('id' => '3502','province' => '35','name' => 'KAB. PONOROGO'),
      array('id' => '3503','province' => '35','name' => 'KAB. TRENGGALEK'),
      array('id' => '3504','province' => '35','name' => 'KAB. TULUNGAGUNG'),
      array('id' => '3505','province' => '35','name' => 'KAB. BLITAR'),
      array('id' => '3506','province' => '35','name' => 'KAB. KEDIRI'),
      array('id' => '3507','province' => '35','name' => 'KAB. MALANG'),
      array('id' => '3508','province' => '35','name' => 'KAB. LUMAJANG'),
      array('id' => '3509','province' => '35','name' => 'KAB. JEMBER'),
      array('id' => '3510','province' => '35','name' => 'KAB. BANYUWANGI'),
      array('id' => '3511','province' => '35','name' => 'KAB. BONDOWOSO'),
      array('id' => '3512','province' => '35','name' => 'KAB. SITUBONDO'),
      array('id' => '3513','province' => '35','name' => 'KAB. PROBOLINGGO'),
      array('id' => '3514','province' => '35','name' => 'KAB. PASURUAN'),
      array('id' => '3515','province' => '35','name' => 'KAB. SIDOARJO'),
      array('id' => '3516','province' => '35','name' => 'KAB. MOJOKERTO'),
      array('id' => '3517','province' => '35','name' => 'KAB. JOMBANG'),
      array('id' => '3518','province' => '35','name' => 'KAB. NGANJUK'),
      array('id' => '3519','province' => '35','name' => 'KAB. MADIUN'),
      array('id' => '3520','province' => '35','name' => 'KAB. MAGETAN'),
      array('id' => '3521','province' => '35','name' => 'KAB. NGAWI'),
      array('id' => '3522','province' => '35','name' => 'KAB. BOJONEGORO'),
      array('id' => '3523','province' => '35','name' => 'KAB. TUBAN'),
      array('id' => '3524','province' => '35','name' => 'KAB. LAMONGAN'),
      array('id' => '3525','province' => '35','name' => 'KAB. GRESIK'),
      array('id' => '3526','province' => '35','name' => 'KAB. BANGKALAN'),
      array('id' => '3527','province' => '35','name' => 'KAB. SAMPANG'),
      array('id' => '3528','province' => '35','name' => 'KAB. PAMEKASAN'),
      array('id' => '3529','province' => '35','name' => 'KAB. SUMENEP'),
      array('id' => '3571','province' => '35','name' => 'KOTA KEDIRI'),
      array('id' => '3572','province' => '35','name' => 'KOTA BLITAR'),
      array('id' => '3573','province' => '35','name' => 'KOTA MALANG'),
      array('id' => '3574','province' => '35','name' => 'KOTA PROBOLINGGO'),
      array('id' => '3575','province' => '35','name' => 'KOTA PASURUAN'),
      array('id' => '3576','province' => '35','name' => 'KOTA MOJOKERTO'),
      array('id' => '3577','province' => '35','name' => 'KOTA MADIUN'),
      array('id' => '3578','province' => '35','name' => 'KOTA SURABAYA'),
      array('id' => '3579','province' => '35','name' => 'KOTA BATU'),
      array('id' => '3601','province' => '36','name' => 'KAB. PANDEGLANG'),
      array('id' => '3602','province' => '36','name' => 'KAB. LEBAK'),
      array('id' => '3603','province' => '36','name' => 'KAB. TANGERANG'),
      array('id' => '3604','province' => '36','name' => 'KAB. SERANG'),
      array('id' => '3671','province' => '36','name' => 'KOTA TANGERANG'),
      array('id' => '3672','province' => '36','name' => 'KOTA CILEGON'),
      array('id' => '3673','province' => '36','name' => 'KOTA SERANG'),
      array('id' => '3674','province' => '36','name' => 'KOTA TANGERANG SELATAN'),
      array('id' => '5101','province' => '51','name' => 'KAB. JEMBRANA'),
      array('id' => '5102','province' => '51','name' => 'KAB. TABANAN'),
      array('id' => '5103','province' => '51','name' => 'KAB. BADUNG'),
      array('id' => '5104','province' => '51','name' => 'KAB. GIANYAR'),
      array('id' => '5105','province' => '51','name' => 'KAB. KLUNGKUNG'),
      array('id' => '5106','province' => '51','name' => 'KAB. BANGLI'),
      array('id' => '5107','province' => '51','name' => 'KAB. KARANGASEM'),
      array('id' => '5108','province' => '51','name' => 'KAB. BULELENG'),
      array('id' => '5171','province' => '51','name' => 'KOTA DENPASAR'),
      array('id' => '5201','province' => '52','name' => 'KAB. LOMBOK BARAT'),
      array('id' => '5202','province' => '52','name' => 'KAB. LOMBOK TENGAH'),
      array('id' => '5203','province' => '52','name' => 'KAB. LOMBOK TIMUR'),
      array('id' => '5204','province' => '52','name' => 'KAB. SUMBAWA'),
      array('id' => '5205','province' => '52','name' => 'KAB. DOMPU'),
      array('id' => '5206','province' => '52','name' => 'KAB. BIMA'),
      array('id' => '5207','province' => '52','name' => 'KAB. SUMBAWA BARAT'),
      array('id' => '5208','province' => '52','name' => 'KAB. LOMBOK UTARA'),
      array('id' => '5271','province' => '52','name' => 'KOTA MATARAM'),
      array('id' => '5272','province' => '52','name' => 'KOTA BIMA'),
      array('id' => '5301','province' => '53','name' => 'KAB. KUPANG'),
      array('id' => '5302','province' => '53','name' => 'KAB TIMOR TENGAH SELATAN'),
      array('id' => '5303','province' => '53','name' => 'KAB. TIMOR TENGAH UTARA'),
      array('id' => '5304','province' => '53','name' => 'KAB. BELU'),
      array('id' => '5305','province' => '53','name' => 'KAB. ALOR'),
      array('id' => '5306','province' => '53','name' => 'KAB. FLORES TIMUR'),
      array('id' => '5307','province' => '53','name' => 'KAB. SIKKA'),
      array('id' => '5308','province' => '53','name' => 'KAB. ENDE'),
      array('id' => '5309','province' => '53','name' => 'KAB. NGADA'),
      array('id' => '5310','province' => '53','name' => 'KAB. MANGGARAI'),
      array('id' => '5311','province' => '53','name' => 'KAB. SUMBA TIMUR'),
      array('id' => '5312','province' => '53','name' => 'KAB. SUMBA BARAT'),
      array('id' => '5313','province' => '53','name' => 'KAB. LEMBATA'),
      array('id' => '5314','province' => '53','name' => 'KAB. ROTE NDAO'),
      array('id' => '5315','province' => '53','name' => 'KAB. MANGGARAI BARAT'),
      array('id' => '5316','province' => '53','name' => 'KAB. NAGEKEO'),
      array('id' => '5317','province' => '53','name' => 'KAB. SUMBA TENGAH'),
      array('id' => '5318','province' => '53','name' => 'KAB. SUMBA BARAT DAYA'),
      array('id' => '5319','province' => '53','name' => 'KAB. MANGGARAI TIMUR'),
      array('id' => '5320','province' => '53','name' => 'KAB. SABU RAIJUA'),
      array('id' => '5321','province' => '53','name' => 'KAB. MALAKA'),
      array('id' => '5371','province' => '53','name' => 'KOTA KUPANG'),
      array('id' => '6101','province' => '61','name' => 'KAB. SAMBAS'),
      array('id' => '6102','province' => '61','name' => 'KAB. MEMPAWAH'),
      array('id' => '6103','province' => '61','name' => 'KAB. SANGGAU'),
      array('id' => '6104','province' => '61','name' => 'KAB. KETAPANG'),
      array('id' => '6105','province' => '61','name' => 'KAB. SINTANG'),
      array('id' => '6106','province' => '61','name' => 'KAB. KAPUAS HULU'),
      array('id' => '6107','province' => '61','name' => 'KAB. BENGKAYANG'),
      array('id' => '6108','province' => '61','name' => 'KAB. LANDAK'),
      array('id' => '6109','province' => '61','name' => 'KAB. SEKADAU'),
      array('id' => '6110','province' => '61','name' => 'KAB. MELAWI'),
      array('id' => '6111','province' => '61','name' => 'KAB. KAYONG UTARA'),
      array('id' => '6112','province' => '61','name' => 'KAB. KUBU RAYA'),
      array('id' => '6171','province' => '61','name' => 'KOTA PONTIANAK'),
      array('id' => '6172','province' => '61','name' => 'KOTA SINGKAWANG'),
      array('id' => '6201','province' => '62','name' => 'KAB. KOTAWARINGIN BARAT'),
      array('id' => '6202','province' => '62','name' => 'KAB. KOTAWARINGIN TIMUR'),
      array('id' => '6203','province' => '62','name' => 'KAB. KAPUAS'),
      array('id' => '6204','province' => '62','name' => 'KAB. BARITO SELATAN'),
      array('id' => '6205','province' => '62','name' => 'KAB. BARITO UTARA'),
      array('id' => '6206','province' => '62','name' => 'KAB. KATINGAN'),
      array('id' => '6207','province' => '62','name' => 'KAB. SERUYAN'),
      array('id' => '6208','province' => '62','name' => 'KAB. SUKAMARA'),
      array('id' => '6209','province' => '62','name' => 'KAB. LAMANDAU'),
      array('id' => '6210','province' => '62','name' => 'KAB. GUNUNG MAS'),
      array('id' => '6211','province' => '62','name' => 'KAB. PULANG PISAU'),
      array('id' => '6212','province' => '62','name' => 'KAB. MURUNG RAYA'),
      array('id' => '6213','province' => '62','name' => 'KAB. BARITO TIMUR'),
      array('id' => '6271','province' => '62','name' => 'KOTA PALANGKARAYA'),
      array('id' => '6301','province' => '63','name' => 'KAB. TANAH LAUT'),
      array('id' => '6302','province' => '63','name' => 'KAB. KOTABARU'),
      array('id' => '6303','province' => '63','name' => 'KAB. BANJAR'),
      array('id' => '6304','province' => '63','name' => 'KAB. BARITO KUALA'),
      array('id' => '6305','province' => '63','name' => 'KAB. TAPIN'),
      array('id' => '6306','province' => '63','name' => 'KAB. HULU SUNGAI SELATAN'),
      array('id' => '6307','province' => '63','name' => 'KAB. HULU SUNGAI TENGAH'),
      array('id' => '6308','province' => '63','name' => 'KAB. HULU SUNGAI UTARA'),
      array('id' => '6309','province' => '63','name' => 'KAB. TABALONG'),
      array('id' => '6310','province' => '63','name' => 'KAB. TANAH BUMBU'),
      array('id' => '6311','province' => '63','name' => 'KAB. BALANGAN'),
      array('id' => '6371','province' => '63','name' => 'KOTA BANJARMASIN'),
      array('id' => '6372','province' => '63','name' => 'KOTA BANJARBARU'),
      array('id' => '6401','province' => '64','name' => 'KAB. PASER'),
      array('id' => '6402','province' => '64','name' => 'KAB. KUTAI KARTANEGARA'),
      array('id' => '6403','province' => '64','name' => 'KAB. BERAU'),
      array('id' => '6407','province' => '64','name' => 'KAB. KUTAI BARAT'),
      array('id' => '6408','province' => '64','name' => 'KAB. KUTAI TIMUR'),
      array('id' => '6409','province' => '64','name' => 'KAB. PENAJAM PASER UTARA'),
      array('id' => '6411','province' => '64','name' => 'KAB. MAHAKAM ULU'),
      array('id' => '6471','province' => '64','name' => 'KOTA BALIKPAPAN'),
      array('id' => '6472','province' => '64','name' => 'KOTA SAMARINDA'),
      array('id' => '6474','province' => '64','name' => 'KOTA BONTANG'),
      array('id' => '6501','province' => '65','name' => 'KAB. BULUNGAN'),
      array('id' => '6502','province' => '65','name' => 'KAB. MALINAU'),
      array('id' => '6503','province' => '65','name' => 'KAB. NUNUKAN'),
      array('id' => '6504','province' => '65','name' => 'KAB. TANA TIDUNG'),
      array('id' => '6571','province' => '65','name' => 'KOTA TARAKAN'),
      array('id' => '7101','province' => '71','name' => 'KAB. BOLAANG MONGONDOW'),
      array('id' => '7102','province' => '71','name' => 'KAB. MINAHASA'),
      array('id' => '7103','province' => '71','name' => 'KAB. KEPULAUAN SANGIHE'),
      array('id' => '7104','province' => '71','name' => 'KAB. KEPULAUAN TALAUD'),
      array('id' => '7105','province' => '71','name' => 'KAB. MINAHASA SELATAN'),
      array('id' => '7106','province' => '71','name' => 'KAB. MINAHASA UTARA'),
      array('id' => '7107','province' => '71','name' => 'KAB. MINAHASA TENGGARA'),
      array('id' => '7108','province' => '71','name' => 'KAB. BOLAANG MONGONDOW UTARA'),
      array('id' => '7109','province' => '71','name' => 'KAB. KEP. SIAU TAGULANDANG BIARO'),
      array('id' => '7110','province' => '71','name' => 'KAB. BOLAANG MONGONDOW TIMUR'),
      array('id' => '7111','province' => '71','name' => 'KAB. BOLAANG MONGONDOW SELATAN'),
      array('id' => '7171','province' => '71','name' => 'KOTA MANADO'),
      array('id' => '7172','province' => '71','name' => 'KOTA BITUNG'),
      array('id' => '7173','province' => '71','name' => 'KOTA TOMOHON'),
      array('id' => '7174','province' => '71','name' => 'KOTA KOTAMOBAGU'),
      array('id' => '7201','province' => '72','name' => 'KAB. BANGGAI'),
      array('id' => '7202','province' => '72','name' => 'KAB. POSO'),
      array('id' => '7203','province' => '72','name' => 'KAB. DONGGALA'),
      array('id' => '7204','province' => '72','name' => 'KAB. TOLI TOLI'),
      array('id' => '7205','province' => '72','name' => 'KAB. BUOL'),
      array('id' => '7206','province' => '72','name' => 'KAB. MOROWALI'),
      array('id' => '7207','province' => '72','name' => 'KAB. BANGGAI KEPULAUAN'),
      array('id' => '7208','province' => '72','name' => 'KAB. PARIGI MOUTONG'),
      array('id' => '7209','province' => '72','name' => 'KAB. TOJO UNA UNA'),
      array('id' => '7210','province' => '72','name' => 'KAB. SIGI'),
      array('id' => '7211','province' => '72','name' => 'KAB. BANGGAI LAUT'),
      array('id' => '7212','province' => '72','name' => 'KAB. MOROWALI UTARA'),
      array('id' => '7271','province' => '72','name' => 'KOTA PALU'),
      array('id' => '7301','province' => '73','name' => 'KAB. KEPULAUAN SELAYAR'),
      array('id' => '7302','province' => '73','name' => 'KAB. BULUKUMBA'),
      array('id' => '7303','province' => '73','name' => 'KAB. BANTAENG'),
      array('id' => '7304','province' => '73','name' => 'KAB. JENEPONTO'),
      array('id' => '7305','province' => '73','name' => 'KAB. TAKALAR'),
      array('id' => '7306','province' => '73','name' => 'KAB. GOWA'),
      array('id' => '7307','province' => '73','name' => 'KAB. SINJAI'),
      array('id' => '7308','province' => '73','name' => 'KAB. BONE'),
      array('id' => '7309','province' => '73','name' => 'KAB. MAROS'),
      array('id' => '7310','province' => '73','name' => 'KAB. PANGKAJENE KEPULAUAN'),
      array('id' => '7311','province' => '73','name' => 'KAB. BARRU'),
      array('id' => '7312','province' => '73','name' => 'KAB. SOPPENG'),
      array('id' => '7313','province' => '73','name' => 'KAB. WAJO'),
      array('id' => '7314','province' => '73','name' => 'KAB. SIDENRENG RAPPANG'),
      array('id' => '7315','province' => '73','name' => 'KAB. PINRANG'),
      array('id' => '7316','province' => '73','name' => 'KAB. ENREKANG'),
      array('id' => '7317','province' => '73','name' => 'KAB. LUWU'),
      array('id' => '7318','province' => '73','name' => 'KAB. TANA TORAJA'),
      array('id' => '7322','province' => '73','name' => 'KAB. LUWU UTARA'),
      array('id' => '7324','province' => '73','name' => 'KAB. LUWU TIMUR'),
      array('id' => '7326','province' => '73','name' => 'KAB. TORAJA UTARA'),
      array('id' => '7371','province' => '73','name' => 'KOTA MAKASSAR'),
      array('id' => '7372','province' => '73','name' => 'KOTA PARE PARE'),
      array('id' => '7373','province' => '73','name' => 'KOTA PALOPO'),
      array('id' => '7401','province' => '74','name' => 'KAB. KOLAKA'),
      array('id' => '7402','province' => '74','name' => 'KAB. KONAWE'),
      array('id' => '7403','province' => '74','name' => 'KAB. MUNA'),
      array('id' => '7404','province' => '74','name' => 'KAB. BUTON'),
      array('id' => '7405','province' => '74','name' => 'KAB. KONAWE SELATAN'),
      array('id' => '7406','province' => '74','name' => 'KAB. BOMBANA'),
      array('id' => '7407','province' => '74','name' => 'KAB. WAKATOBI'),
      array('id' => '7408','province' => '74','name' => 'KAB. KOLAKA UTARA'),
      array('id' => '7409','province' => '74','name' => 'KAB. KONAWE UTARA'),
      array('id' => '7410','province' => '74','name' => 'KAB. BUTON UTARA'),
      array('id' => '7411','province' => '74','name' => 'KAB. KOLAKA TIMUR'),
      array('id' => '7412','province' => '74','name' => 'KAB. KONAWE KEPULAUAN'),
      array('id' => '7413','province' => '74','name' => 'KAB. MUNA BARAT'),
      array('id' => '7414','province' => '74','name' => 'KAB. BUTON TENGAH'),
      array('id' => '7415','province' => '74','name' => 'KAB. BUTON SELATAN'),
      array('id' => '7471','province' => '74','name' => 'KOTA KENDARI'),
      array('id' => '7472','province' => '74','name' => 'KOTA BAU BAU'),
      array('id' => '7501','province' => '75','name' => 'KAB. GORONTALO'),
      array('id' => '7502','province' => '75','name' => 'KAB. BOALEMO'),
      array('id' => '7503','province' => '75','name' => 'KAB. BONE BOLANGO'),
      array('id' => '7504','province' => '75','name' => 'KAB. PAHUWATO'),
      array('id' => '7505','province' => '75','name' => 'KAB. GORONTALO UTARA'),
      array('id' => '7571','province' => '75','name' => 'KOTA GORONTALO'),
      array('id' => '7601','province' => '76','name' => 'KAB. MAMUJU UTARA'),
      array('id' => '7602','province' => '76','name' => 'KAB. MAMUJU'),
      array('id' => '7603','province' => '76','name' => 'KAB. MAMASA'),
      array('id' => '7604','province' => '76','name' => 'KAB. POLEWALI MANDAR'),
      array('id' => '7605','province' => '76','name' => 'KAB. MAJENE'),
      array('id' => '7606','province' => '76','name' => 'KAB. MAMUJU TENGAH'),
      array('id' => '8101','province' => '81','name' => 'KAB. MALUKU TENGAH'),
      array('id' => '8102','province' => '81','name' => 'KAB. MALUKU TENGGARA'),
      array('id' => '8103','province' => '81','name' => 'KAB. MALUKU TENGGARA BARAT'),
      array('id' => '8104','province' => '81','name' => 'KAB. BURU'),
      array('id' => '8105','province' => '81','name' => 'KAB. SERAM BAGIAN TIMUR'),
      array('id' => '8106','province' => '81','name' => 'KAB. SERAM BAGIAN BARAT'),
      array('id' => '8107','province' => '81','name' => 'KAB. KEPULAUAN ARU'),
      array('id' => '8108','province' => '81','name' => 'KAB. MALUKU BARAT DAYA'),
      array('id' => '8109','province' => '81','name' => 'KAB. BURU SELATAN'),
      array('id' => '8171','province' => '81','name' => 'KOTA AMBON'),
      array('id' => '8172','province' => '81','name' => 'KOTA TUAL'),
      array('id' => '8201','province' => '82','name' => 'KAB. HALMAHERA BARAT'),
      array('id' => '8202','province' => '82','name' => 'KAB. HALMAHERA TENGAH'),
      array('id' => '8203','province' => '82','name' => 'KAB. HALMAHERA UTARA'),
      array('id' => '8204','province' => '82','name' => 'KAB. HALMAHERA SELATAN'),
      array('id' => '8205','province' => '82','name' => 'KAB. KEPULAUAN SULA'),
      array('id' => '8206','province' => '82','name' => 'KAB. HALMAHERA TIMUR'),
      array('id' => '8207','province' => '82','name' => 'KAB. PULAU MOROTAI'),
      array('id' => '8208','province' => '82','name' => 'KAB. PULAU TALIABU'),
      array('id' => '8271','province' => '82','name' => 'KOTA TERNATE'),
      array('id' => '8272','province' => '82','name' => 'KOTA TIDORE KEPULAUAN'),
      array('id' => '9101','province' => '91','name' => 'KAB. MERAUKE'),
      array('id' => '9102','province' => '91','name' => 'KAB. JAYAWIJAYA'),
      array('id' => '9103','province' => '91','name' => 'KAB. JAYAPURA'),
      array('id' => '9104','province' => '91','name' => 'KAB. NABIRE'),
      array('id' => '9105','province' => '91','name' => 'KAB. KEPULAUAN YAPEN'),
      array('id' => '9106','province' => '91','name' => 'KAB. BIAK NUMFOR'),
      array('id' => '9107','province' => '91','name' => 'KAB. PUNCAK JAYA'),
      array('id' => '9108','province' => '91','name' => 'KAB. PANIAI'),
      array('id' => '9109','province' => '91','name' => 'KAB. MIMIKA'),
      array('id' => '9110','province' => '91','name' => 'KAB. SARMI'),
      array('id' => '9111','province' => '91','name' => 'KAB. KEEROM'),
      array('id' => '9112','province' => '91','name' => 'KAB. PEGUNUNGAN BINTANG'),
      array('id' => '9113','province' => '91','name' => 'KAB. YAHUKIMO'),
      array('id' => '9114','province' => '91','name' => 'KAB. TOLIKARA'),
      array('id' => '9115','province' => '91','name' => 'KAB. WAROPEN'),
      array('id' => '9116','province' => '91','name' => 'KAB. BOVEN DIGOEL'),
      array('id' => '9117','province' => '91','name' => 'KAB. MAPPI'),
      array('id' => '9118','province' => '91','name' => 'KAB. ASMAT'),
      array('id' => '9119','province' => '91','name' => 'KAB. SUPIORI'),
      array('id' => '9120','province' => '91','name' => 'KAB. MAMBERAMO RAYA'),
      array('id' => '9121','province' => '91','name' => 'KAB. MAMBERAMO TENGAH'),
      array('id' => '9122','province' => '91','name' => 'KAB. YALIMO'),
      array('id' => '9123','province' => '91','name' => 'KAB. LANNY JAYA'),
      array('id' => '9124','province' => '91','name' => 'KAB. NDUGA'),
      array('id' => '9125','province' => '91','name' => 'KAB. PUNCAK'),
      array('id' => '9126','province' => '91','name' => 'KAB. DOGIYAI'),
      array('id' => '9127','province' => '91','name' => 'KAB. INTAN JAYA'),
      array('id' => '9128','province' => '91','name' => 'KAB. DEIYAI'),
      array('id' => '9171','province' => '91','name' => 'KOTA JAYAPURA'),
      array('id' => '9201','province' => '92','name' => 'KAB. SORONG'),
      array('id' => '9202','province' => '92','name' => 'KAB. MANOKWARI'),
      array('id' => '9203','province' => '92','name' => 'KAB. FAK FAK'),
      array('id' => '9204','province' => '92','name' => 'KAB. SORONG SELATAN'),
      array('id' => '9205','province' => '92','name' => 'KAB. RAJA AMPAT'),
      array('id' => '9206','province' => '92','name' => 'KAB. TELUK BINTUNI'),
      array('id' => '9207','province' => '92','name' => 'KAB. TELUK WONDAMA'),
      array('id' => '9208','province' => '92','name' => 'KAB. KAIMANA'),
      array('id' => '9209','province' => '92','name' => 'KAB. TAMBRAUW'),
      array('id' => '9210','province' => '92','name' => 'KAB. MAYBRAT'),
      array('id' => '9211','province' => '92','name' => 'KAB. MANOKWARI SELATAN'),
      array('id' => '9212','province' => '92','name' => 'KAB. PEGUNUNGAN ARFAK'),
      array('id' => '9271','province' => '92','name' => 'KOTA SORONG')
    );
    Kabupaten::insert($regencies);
  }
}
